configuration:

  server:
    listenAddr: :8080 #default
    requestTimeout: 30s # end-to-end request timeout
    
  auth:
    gitlabBaseUrl: https://gitlab.com
    authCacheTtl: 10m # Duration to cache successful PAT verifications.
    
  sonatype:
    upstream: https://ossindex.sonatype.org/api/v3/component-report # shouldn't need changing
    username: <Your SonaType Username>
    apiKey: <Your SonaType API key>
    timeout: 20s

  cache:
    directory: test
    refreshTtl: 8h # time until reports become eligible for being refreshed, since their last retrieval.
    expireTtl: 96h # time until reports become expired, since their last retrieval, and can no longer be used unless re-acquired from upstream.
    unusedTtl: 120h # how long since a report is last accessed before it's evicted from the cache entirely
    batchSize: 100 # when refreshing cache, the maximum number of reports to retrieve in a single request.
    
  logs:
    # journal: # if configured, specifies the journal name for journalctl, if not configured, the process name is used.

